### ISSUE TITLE
[Anon] Bug report: Dindrenzi_Ground_Forces.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/firestorm-planetfall#32]
**File:** Dindrenzi_Ground_Forces.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** Directorate - Recon Helix: The orbat allows, to field TWO transporters (one for the light one, one for the heavy one...). The Datafile allows just, two field ONE transporter for the light infantery. There is no option, to field the other for the heavies. Hope, I was able to point the problem out. Greetings! Heiko

**Comment by steve990** [comment]
This should be corrected in the latest release to make the transports mandatory. Thanks for the report!
