### ISSUE TITLE
[Anon] Bug report: Relthozan_Ground_Forces.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/firestorm-planetfall#36]
**File:** Relthozan_Ground_Forces.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Only 1 halamasc is posible in battlescribe. Obligatory 3 un the orbat

**Comment by steve990** [comment]
Halamasc squadron size corrected.
