### ISSUE TITLE
[Anon] Bug report: Terran_Alliance_Ground_Forces.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/firestorm-planetfall#41]
**File:** Terran_Alliance_Ground_Forces.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** Terran alliance Sinir medium transport points cost is incorrect. Revised down to 85 points from 90 in recent ORBAT update. Points are incorrect in both core and recon helixes where it can be taken.

**Comment by steve990** [comment]
Should be fixed now. Thanks for the comments!
